imgs = {
    # ROLES
    "https://imgur.com/a/VQu2oWu \nhttps://imgur.com/a/YncwTNB": ["audit"],
    "https://imgur.com/a/lWOEpm8": ["town", "town roles"],
    "https://imgur.com/a/ns9Vm6p": ["justice", "town justice"],
    "https://imgur.com/a/EMdz59o": ["sharpshooter"],
    "https://imgur.com/a/IqHr2Qi": ["veteran"],
    "https://imgur.com/a/sqFh9Xk": ["discovery", "town discovery"],
    "https://imgur.com/a/QTl9YfU": ["detective"],
    "https://imgur.com/a/vIg6nOC": ["lookout"],
    "https://imgur.com/a/edUBTYt": ["protection", "town protection"],
    "https://imgur.com/a/i792CSV": ["chef", "cook"],
    "https://imgur.com/a/pPhdlVC": ["doctor"],
    "https://imgur.com/a/GnUUflQ": ["support", "town support"],
    "https://imgur.com/a/OZANS8D": ["cia", "cia op", "cia operative"],
    "https://imgur.com/a/Qr15Ic4": ["graverobber", "grave", "robber"],
    "https://imgur.com/a/2RUsrWP": ["town crier", "crier"],
    "https://imgur.com/a/yM0ytAT": ["multipurpose", "town multipurpose"],
    "https://imgur.com/a/dB8JRGD": ["cyborg"],
    "https://imgur.com/a/f395XyV": ["director"],
    "https://imgur.com/a/FW5NXlI": ["mafia", "mafia roles"],
    "https://imgur.com/a/A7RQQMq": ["leader", "mafia leader"],
    "https://imgur.com/a/by1GCmk": ["godfather", "gf"],
    "https://imgur.com/a/pgZxNEP": ["killing", "mafia killing"],
    "https://imgur.com/a/XQ5pCHd": ["arsonist", "oil"],
    "https://imgur.com/a/kIprBUq": ["bomber"],
    "https://imgur.com/a/UkqHG9t": ["disruption", "mafia disruption"],
    "https://imgur.com/a/R4D4lsD": ["cloner"],
    "https://imgur.com/a/6hXffWz": ["ransomist", "ransom"],
    "https://imgur.com/a/2WHeNVB": ["neutral", "neutral roles"],
    "https://imgur.com/a/jxPfinm": ["neutral independent", "independent", "ind", "ni"],
    "https://imgur.com/a/RYtjsYI": ["jester"],
    "https://imgur.com/a/NAQPUuO": ["chaos", "neutral chaos"],
    "https://imgur.com/a/n9IBDnd": ["hypnotist"],
    "https://imgur.com/a/N5g6DAx": ["puppet", "puppeteer"],
    "https://imgur.com/a/CriPMbt": ["destruction", "neutral destruction"],
    "https://imgur.com/a/rpXlq07": ["werewolf"],

    # KEYWORDS
    "https://imgur.com/a/6RgqXyz": ["abilities"],
    "https://imgur.com/a/IHRy9rv": ["death"],
    "https://imgur.com/a/pFA08lO": ["croak", "croak vote"],
    "https://imgur.com/a/p31TbxQ": ["letters"],
    "https://imgur.com/a/1EZ1WXA": ["events"],
    "https://imgur.com/a/eaNzfRS": ["win conditions", "win"],
    "https://imgur.com/a/rBk5hE7": ["kill", "defense", "basic kill", "basic defense", "powerful kill", "powerful defense", "obliteration", "invincibility"],
    "https://imgur.com/a/opyQjzb": ["passives"],
    "https://imgur.com/a/Cz7EjCX": ["alert", "announcement"],
    "https://imgur.com/a/aonq8F3": ["witness", "witness protection", "protection"],
    "https://imgur.com/a/Nqm67Ie": ["intermission", "break"],
    "https://imgur.com/a/oKM6ESG": ["tips", "game tips"],
    "https://imgur.com/a/m7HFNT1": ["status"],
    "https://imgur.com/a/twOn1c4": ["mark"],
    "https://imgur.com/a/LGSWtYD": ["offer"],
    "https://imgur.com/a/gTTCCjM": ["item"],
    "https://imgur.com/a/6Tift0v": ["resource"],
    "https://imgur.com/a/Q49ZGDV": ["modifiers", "ability modifiers"],
    "https://imgur.com/a/YncwTNB": [], # NOTE: audit is already a keyword...
    "https://imgur.com/a/8jbd15K": ["roleblock", "block"],
    "https://imgur.com/a/w3tr7ml": ["erase"],
    "https://imgur.com/a/nnrrB1r": ["disguise"],
    "https://imgur.com/a/relCFQD": ["ability fail", "alignment", "dawn", "dusk", "district", "follower", "retrieve", "new", "visit"],
    "https://imgur.com/a/GLJSSEM": ["alerts"], # NOTE: too many things say alert wah
    "https://imgur.com/a/wSEhfhd": ["consistent announcements"], # NOTE: TOO MANY THINGS SAY ANNOUNCEMENTS AND STUFF
    "https://imgur.com/a/PDOkgrJ": ["offers"],
    "https://imgur.com/a/XTVMTTY": ["statuses"],
    "https://imgur.com/a/c7ATQiD": ["marks"],
    "https://imgur.com/a/AZZyHYK": ["resources"],
    "https://imgur.com/a/S1fee5B": ["items"],

    # FUN THINGS
    "https://imgur.com/a/Alcn8bl": ["nyan", "gamation"],
    "https://imgur.com/a/pn6Oygi": ["mafiakeywords"],
    """The missile knows where it is at all times. It knows this because it knows where it isn't, by subtracting where it is, from where it isn't, or where it isn't, from where it is, whichever is greater, it obtains a difference, or deviation. The guidance sub-system uses deviations to generate corrective commands to drive the missile from a position where it is, to a position where it isn't, and arriving at a position where it wasn't, it now is. Consequently, the position where it is, is now the position that it wasn't, and it follows that the position where it was, is now the position that it isn't. In the event of the position that it is in is not the position that it wasn't, the system has required a variation. The variation being the difference between where the missile is, and where it wasn't. If variation is considered to be a significant factor, it too, may be corrected by the GEA. However, the missile must also know where it was. The missile guidance computance scenario works as follows: Because a variation has modified some of the information the missile has obtained, it is not sure just where it is, however it is sure where it isn't, within reason, and it knows where it was. It now subracts where it should be, from where it wasn't, or vice versa. By differentiating this from the algebraic sum og where it shouldn't be, and where it was. It is able to obtain a deviation, and a variation, which is called "air".""": ["missile"],
    "woost...": ["fore", "4", "74"],
}