imgs = {
    # ROLES
    "https://imgur.com/a/kilmDO3": ["audit"],
    "https://imgur.com/a/An0VNeV": ["town", "town roles"],
    "https://imgur.com/a/9HwK8FD": ["justice", "town justice", "town violence", "violence"],
    "https://imgur.com/a/UNYD197": ["gun nut", "gun", "nra"],
    "https://imgur.com/a/Q5Jr7Tf": ["seattle police officer", "seattle", "police", "officer", "police officer", "spd"],
    "https://imgur.com/a/upBQoSB": ["tack shooter", "tack", "shooter", "bloons"],
    "https://imgur.com/a/lu3RMh7": ["discovery", "town discovery", "thinking", "town thinking"],
    "https://imgur.com/a/8bnT9m4": ["coronee"],
    "https://imgur.com/a/zKC0lSD": ["fire lookout station", "fire", "lookout", "fire lookout", "lookout station"],
    "https://imgur.com/a/cY4oPXR": ["gumshoe", "detective"],
    "https://imgur.com/a/XMaIx8r": ["gum shoe", "shoe"],
    "https://imgur.com/a/Q2Nr8y1": ["protection", "town protection", "malpractice", "town malpractice"],
    "https://imgur.com/a/66CAYig": ["bouncer"],
    "https://imgur.com/a/rGKfsxT": ["doctor", "doctor of philosophy", "phd"],
    "https://imgur.com/a/sNUgFgV": ["house", "house m.d.", "house md"],
    "https://imgur.com/a/2fGlX5l": ["support", "town support", "nightmare", "town nightmare"],
    "https://imgur.com/a/ilpC0HW": ["bruce willis", "willis", "bruce"],
    "https://imgur.com/a/6befWgq": ["mario (from mario)", "mario"],
    "https://imgur.com/a/aUnM6Qv": ["my brother", "brother"],
    "https://imgur.com/a/Un01H7q": ["multipurpose", "town multipurpose"],
    "https://imgur.com/a/mlwzFxl": ["artificial intelligence", "ai"],
    "https://imgur.com/a/0YvxOzQ": ["pokemon trainer", "trainer"],
    "https://imgur.com/a/gQ6nTJ1": ["washington monument", "washington", "monument"],
    "https://imgur.com/a/c8JwZdb": ["mafia", "mafia roles"],
    "https://imgur.com/a/2rJ7hW6": ["leader", "mafia leader", "matriarch", "mafia matriarch"],
    "https://imgur.com/a/zpKQ618": ["grandmother", "gm", "gf"],
    "https://imgur.com/a/NjmeDEM": ["killing", "mafia killing", "maddener", "mafia maddener", "mad"],
    "https://imgur.com/a/cCpjZSv": ["citrea", "oil"],
    "https://imgur.com/a/g8mMTtZ": ["bomber", "unabomber", "ted", "ted kaczynski", "theodore kaczynski", "theodore j. kaczynski"],
    "https://imgur.com/a/kjyyh4q": ["conductor", "band conductor", "hs band conductor", "high school band conductor"],
    "https://imgur.com/a/Yu0yxNS": ["ten thousand bees", "10000 bees", "bees"],
    "https://imgur.com/a/mEYcBDP": ["disruption", "mafia disruption", "center-right", "mafia center-right", "right", "center"],
    "https://imgur.com/a/kGxuTOo": ["anthony j. fauci", "anthony fauci", "fauci"],
    "https://imgur.com/a/BZbnstZ": ["joe biden", "biden"],
    "https://imgur.com/a/EFfKWjG": ["landlord"],
    "https://imgur.com/a/5rlVjuy": ["neutral", "neutral roles"],
    "https://imgur.com/a/z96aMRY": ["neutral independent", "independent"]
    "https://imgur.com/a/EWfDAJV": ["android", "samsung"],
    "https://imgur.com/a/05k3gDm": ["evil jester", "jester"],
    "https://imgur.com/a/9svOdEY": ["god's drunkest driver", "drunk driver", "driver"],
    "https://imgur.com/a/PRY0qQT": ["high roller", "gambler", "roller"],
    "https://imgur.com/a/b0bQJq0": ["neutral chaos but more", "chaos", "neutral chaos"],
    "https://imgur.com/a/0wiwI5j": ["pests"],
    "https://imgur.com/a/4UvPtJB": ["rat", "ratatouille"],
    "https://imgur.com/a/qS6wsoN": ["destruction", "neutral destruction"],
    "https://imgur.com/a/PQnHI6a \nhttps://imgur.com/a/UUkDAse": ["bartender", "ceo", "rule bender"],
    "https://imgur.com/a/nejdJqu": ["woke left", "the woke left", "woke", "left"],

    # KEYWORDS
    "https://imgur.com/a/6RgqXyz": ["abilities"],
    "https://imgur.com/a/IHRy9rv": ["death"],
    "https://imgur.com/a/pFA08lO": ["croak", "croak vote"],
    "https://imgur.com/a/p31TbxQ": ["letters"],
    "https://imgur.com/a/1EZ1WXA": ["events"],
    "https://imgur.com/a/eaNzfRS": ["win conditions", "win"],
    "https://imgur.com/a/rBk5hE7": ["kill", "defense", "basic kill", "basic defense", "powerful kill", "powerful defense", "obliteration", "invincibility"],
    "https://imgur.com/a/opyQjzb": ["passives"],
    "https://imgur.com/a/Cz7EjCX": ["alert", "announcement"],
    "https://imgur.com/a/aonq8F3": ["witness", "witness protection", "protection"],
    "https://imgur.com/a/Nqm67Ie": ["intermission", "break"],
    "https://imgur.com/a/oKM6ESG": ["tips", "game tips"],
    "https://imgur.com/a/m7HFNT1": ["status"],
    "https://imgur.com/a/twOn1c4": ["mark"],
    "https://imgur.com/a/LGSWtYD": ["offer"],
    "https://imgur.com/a/gTTCCjM": ["item"],
    "https://imgur.com/a/6Tift0v": ["resource"],
    "https://imgur.com/a/Q49ZGDV": ["modifiers", "ability modifiers"],
    "https://imgur.com/a/YncwTNB": [], # NOTE: audit is already a keyword...
    "https://imgur.com/a/8jbd15K": ["roleblock", "block"],
    "https://imgur.com/a/w3tr7ml": ["erase"],
    "https://imgur.com/a/nnrrB1r": ["disguise"],
    "https://imgur.com/a/relCFQD": ["ability fail", "alignment", "dawn", "dusk", "district", "follower", "retrieve", "new", "visit"],
    "https://imgur.com/a/GLJSSEM": ["alerts"], # NOTE: too many things say alert wah
    "https://imgur.com/a/wSEhfhd": ["consistent announcements"], # NOTE: TOO MANY THINGS SAY ANNOUNCEMENTS AND STUFF
    "https://imgur.com/a/89iluvU": ["offers"],
    "https://imgur.com/a/lbQyFsl": ["statuses"],
    "https://imgur.com/a/4KrKfVI": ["marks"],
    "https://imgur.com/a/ycanrH4": ["resources"],
    "https://imgur.com/a/6Z6PUBq": ["items"],
    "https://imgur.com/a/1YyMt5P": ["drinks"],

    # FUN THINGS
    "https://imgur.com/a/Alcn8bl": ["nyan", "gamation"],
    "https://imgur.com/a/pn6Oygi": ["mafiakeywords"],
    """The missile knows where it is at all times. It knows this because it knows where it isn't, by subtracting where it is, from where it isn't, or where it isn't, from where it is, whichever is greater, it obtains a difference, or deviation. The guidance sub-system uses deviations to generate corrective commands to drive the missile from a position where it is, to a position where it isn't, and arriving at a position where it wasn't, it now is. Consequently, the position where it is, is now the position that it wasn't, and it follows that the position where it was, is now the position that it isn't. In the event of the position that it is in is not the position that it wasn't, the system has required a variation. The variation being the difference between where the missile is, and where it wasn't. If variation is considered to be a significant factor, it too, may be corrected by the GEA. However, the missile must also know where it was. The missile guidance computance scenario works as follows: Because a variation has modified some of the information the missile has obtained, it is not sure just where it is, however it is sure where it isn't, within reason, and it knows where it was. It now subracts where it should be, from where it wasn't, or vice versa. By differentiating this from the algebraic sum og where it shouldn't be, and where it was. It is able to obtain a deviation, and a variation, which is called "air".""": ["missile"],
    "woost...": ["fore", "4", "74"],
}