imgs = {
    # ROLES
    "https://imgur.com/a/IPum3Ms \nhttps://imgur.com/a/YncwTNB": ["audit"],
    "https://imgur.com/a/jnqe6Z9": ["town", "town roles"],
    "https://imgur.com/a/bWp9aGN": ["justice", "town justice", "apollo"],
    "https://imgur.com/a/Eb3bf8A": ["gunslinger", "hunt", "spray and pray"],
    "https://imgur.com/a/sobPnBS": ["sharpshooter", "snipe", "public execution"],
    "https://imgur.com/a/JdxpFir": ["sheriff", "reputation", "shoot"],
    "https://imgur.com/a/IMFvh4m": ["veteran", "high alert", "ready, aim, fire"],
    "https://imgur.com/a/HpattE6": ["discovery", "town discovery"],
    "https://imgur.com/a/JzDBbWk": ["coroner", "gather prints", "autopsy report", "postmortem"],
    "https://imgur.com/a/5EFkrr2": ["detective", "process of elimination", "further investigation"],
    "https://imgur.com/a/XD7bRVR": ["gumshoe", "educated guess", "breakthrough"],
    "https://imgur.com/a/45T07y5": ["lookout", "watch", "track"],
    "https://imgur.com/a/I6Dx7lE": ["protection", "town protection"],
    "https://imgur.com/a/uoiu2Ex": ["bodyguard", "body armor", "guard"],
    "https://imgur.com/a/5RBAfmb": ["chef", "cook", "delicious dish", "base meal", "savory meal", "sweet meal", "stew", "charcuterie", "cheesecake", "bissy"],
    "https://imgur.com/a/S7boiCI": ["doctor", "heal", "self-heal"],
    "https://imgur.com/a/NWwTdfi": ["surgeon", "urgent practices", "miracle cure"],
    "https://imgur.com/a/tForEWY": ["support", "town support"],
    "https://imgur.com/a/yqqKocl": ["courier", "calligraphist", "mail delivery", "final message", "mailman"],
    "https://imgur.com/a/onJ8XVE": ["fortune", "teller", "fortune teller", "sign", "neptune", "uranus", "saturn", "jupiter", "mars", "earth", "moon", "venus", "mercury", "sun"],
    "https://imgur.com/a/Urzfmx5": ["judge", "overrule", "midnight trial"],
    "https://imgur.com/a/2g8pZzM": ["tomb raider", "redistribution", "pawn shop", "everything must go"],
    "https://imgur.com/a/Tqm3CJl": ["multipurpose", "town multipurpose"],
    "https://imgur.com/a/wNnc2L8": ["angler", "fisher", "reel"],
    "https://imgur.com/a/yQ0pz6Y": ["cyborg", "batteries", "power: on", "/query", "/secure", "/terminate", "/charge"],
    "https://imgur.com/a/pkFM3En": ["director", "birdie, hounder, and ladybug", "birdie", "hounder", "ladybug", "system reset", "scared"],
    "https://imgur.com/a/G1TKHzz": ["gravedigger", "gravedig", "exhume", "yorick"],
    "https://imgur.com/a/O16KrvR": ["mafia", "mafia roles"],
    "https://imgur.com/a/CajKVH9": ["leader", "mafia leader"],
    "https://imgur.com/a/6yJXYAR": ["godfather", "gf", "iron fist", "the red hand", "massacre"],
    "https://imgur.com/a/CXtwpXx": ["killing", "mafia killing"],
    "https://imgur.com/a/i6VmTFC": ["assassin", "target", "assassinate", "ass"],
    "https://imgur.com/a/oSoXkyT": ["bomber", "plant", "detonate", "oppenheimer", "anti-barbie"],
    "https://imgur.com/a/dXvcUUJ": ["conductor", "conduct", "tesla coil", "lightning", "pom pom"],
    "https://imgur.com/a/AA2DaBU": ["disruption", "mafia disruption"],
    "https://imgur.com/a/eITrs4Q": ["cloner", "replicate", "hide", "clone her? i hardly know her!"],
    "https://imgur.com/a/qSrC9Ej": ["mortician", "cremation"],
    "https://imgur.com/a/4ojZ7Ob": ["ransomist", "threaten", "the ultimate price", "extortion"],
    "https://imgur.com/a/vkEGp8N": ["neutral", "neutral roles"],
    "https://imgur.com/a/ppqYKKG": ["independent", "neutral independent"],
    "https://imgur.com/a/R1nEVUr": ["apprentice", "quick learner", "teacher"],
    "https://imgur.com/a/ZMsOUc6": ["capitalist", "gross profit", "replenishment order", "earnings guidance", "monopoly man", "shop", "stock", "capital", "auction"],
    "https://imgur.com/a/TI7262e": ["jester", "the last laugh", "prank", "clown", "honk honk", "joker", "jimbo"],
    "https://imgur.com/a/O5DQeUf": ["mercenary", "neutral mercenary"],
    "https://imgur.com/a/ZOGoHLb": ["drunk driver", "dd", "collateral damage", "1.00 bac", "booze 'n' cruise", "end of the road", "passenger", "disembark", "val", "valkyria"],
    "https://imgur.com/a/aokpWht": ["executioner", "nemesis", "lifelong grudge", "tie the noose", "vilify", "darius"],
    "https://imgur.com/a/4M9t0XE": ["chaos", "neutral chaos", "jevil"],
    "https://imgur.com/a/s0HkBQ9": ["hypnotist", "hypnotize", "power of suggestion"],
    "https://imgur.com/a/ZjQnJaN": ["poltergeist", "ratatouille", "possession", "possessed"],
    "https://imgur.com/a/XTR5HAM": ["destruction", "neutral destruction"],
    "https://imgur.com/a/jIr1PXw": ["serial killer", "cereal killer", "jack the ripper", "purple guy", "psychotic tendencies"],
    "https://imgur.com/a/GKgdVNc": ["werewolf", "full moon", "rend", "warwick", "awooo", "orchid", "vander"],

    # KEYWORDS
    "https://imgur.com/a/GKtorLF": ["abilities"],
    "https://imgur.com/a/jPRCyKP": ["death"],
    "https://imgur.com/a/zv1zNVN": ["croak", "croak vote"],
    "https://imgur.com/a/3zamjpn": ["letters"],
    "https://imgur.com/a/6NGvlso": ["events"],
    "https://imgur.com/a/u1mpavV": ["win conditions", "win"],
    "https://imgur.com/a/rBk5hE7": ["kill", "defense", "basic kill", "basic defense", "powerful kill", "powerful defense", "obliteration", "invincibility"],
    "https://imgur.com/a/opyQjzb": ["passives"],
    "https://imgur.com/a/yp1FN1r": ["alert", "discovery", "announcement"],
    "https://imgur.com/a/KehZySv": ["witness", "witness protection", "protection"],
    "https://imgur.com/a/Nqm67Ie": ["intermission", "break"],
    "https://imgur.com/a/oKM6ESG": ["tips", "game tips"],
    "https://imgur.com/a/frZCGrE": ["status"],
    "https://imgur.com/a/iVofK7o": ["mark"],
    "https://imgur.com/a/OtQ1WTV": ["offer"],
    "https://imgur.com/a/FwHeoLy": ["item"],
    "https://imgur.com/a/5iWdNAM": ["resource"],
    "https://imgur.com/a/C3HTOiw": ["action order"],
    "https://imgur.com/a/Q49ZGDV": ["modifiers", "ability modifiers"],
    "https://imgur.com/a/YncwTNB": [], # NOTE: audit is already a keyword...
    "https://imgur.com/a/8jbd15K": ["roleblock", "block"],
    "https://imgur.com/a/yTJRv7M": ["erase"],
    "https://imgur.com/a/1Ul0Um0": ["disguise"],
    "https://imgur.com/a/NYbilZv": ["ability fail", "alignment", "dawn", "dusk", "district", "follower", "retrieve", "new", "visit"],
    "https://imgur.com/a/RztkNC2": ["alerts", "consistent alerts"], # NOTE: too many things say alert wah
    "https://imgur.com/a/LThTaTG": ["discoveries", "consistent alerts"],
    "https://imgur.com/a/TgAUvZP": ["announcements", "consistent announcements"], # NOTE: TOO MANY THINGS SAY ANNOUNCEMENTS AND STUFF
    "https://imgur.com/a/mPKuiAS": ["statuses"],
    "https://imgur.com/a/R8Z0Oyg": ["marks"],
    "https://imgur.com/a/HubnAtc": ["offers"],
    "https://imgur.com/a/y3Evqty": ["resources"],
    "https://imgur.com/a/quJMual": ["rank0", "rank 0 items", "pager", "coupon", "megaphone", "foggy monocle", "child's smoking pipe", "prop gun", "mail parcel", "blindfold", "clown shoes", "romeo's gun"],
    "https://imgur.com/a/zdXoLFI": ["rank1", "rank 1 items", "everclear shot", "medkit", "handgun", "monocle", "toolbox", "scalpel", "wiretap", "voodoo doll", "adrenaline", "bleach", "fake id", "priority mail", "sleep monitor", "red flag"],
    "https://imgur.com/a/nHDsM8T": ["rank2", "rank 2 items", "last will", "magic powder", "security camera", "smoke grenade", "clown nose", "bear trap", "extra ballots", "fishing rod", "bath bomb", "mixed drink", "inheritance", "clown horn", "swiss army knife", "barricade", "gunk bomb"],
    "https://imgur.com/a/i0hgfXz": ["rank3", "rank 3 items", "steroids", "sniper rifle", "master cookbook", "sherlock's monocle", "skeleton key", "tracking device", "philosopher's stone", "visibility cloak", "pocket watch", "furnace"],
    "https://imgur.com/a/XJHOYKQ": ["rank4", "rank 4 items", "second life", "dominion", "machine gun", "storybook", "pocket rat"],

    # FUN THINGS
    "https://imgur.com/a/Alcn8bl": ["bissy"],
    "https://imgur.com/a/pn6Oygi": ["mafiakeywords"],
    """The missile knows where it is at all times. It knows this because it knows where it isn't, by subtracting where it is, from where it isn't, or where it isn't, from where it is, whichever is greater, it obtains a difference, or deviation. The guidance sub-system uses deviations to generate corrective commands to drive the missile from a position where it is, to a position where it isn't, and arriving at a position where it wasn't, it now is. Consequently, the position where it is, is now the position that it wasn't, and it follows that the position where it was, is now the position that it isn't. In the event of the position that it is in is not the position that it wasn't, the system has required a variation. The variation being the difference between where the missile is, and where it wasn't. If variation is considered to be a significant factor, it too, may be corrected by the GEA. However, the missile must also know where it was. The missile guidance computance scenario works as follows: Because a variation has modified some of the information the missile has obtained, it is not sure just where it is, however it is sure where it isn't, within reason, and it knows where it was. It now subracts where it should be, from where it wasn't, or vice versa. By differentiating this from the algebraic sum og where it shouldn't be, and where it was. It is able to obtain a deviation, and a variation, which is called "air".""": ["missile"],
    "woost...": ["fore", "4", "74"],
    """Hi, I'm Quinnigan""": ["quinnigan"]
}